sudo: required
language: php

services:
  - docker

language: php

php:
    - 5.6

before_script:
  - 'sudo apt-get install nodejs-legacy'
  - 'npm install'

script:
  - 'sudo ./node_modules/.bin/grunt'
