sudo: required

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version
  - docker-comspose up -d

before_script: 'composer install'

script: 'vendor/bin/phpunit'