version: "3.5"

services:
  prestashop15:
    image: prestashop/prestashop:1.5-5.5-apache
    depends_on:
      - db-ps15
    environment:
      - PS_DEV_MODE=0
      - PS_COUNTRY=ES
      - PS_DOMAIN=prestashop15-test.docker:8015
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps15
      - DB_NAME=prestashop15
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    ports:
      - "8015:80"
    extra_hosts:
      - "prestashop15-test.docker:127.0.0.1"
  prestashop16:
    image: prestashop/prestashop:1.6.1.20
    depends_on:
      - db-ps16
    environment:
      - PS_DEV_MODE=0
      - PS_COUNTRY=ES
      - PS_DOMAIN=prestashop16-test.docker:8016
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps16
      - DB_NAME=prestashop16
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    ports:
      - "8016:80"
    extra_hosts:
    - "prestashop16-test.docker:127.0.0.1"
  prestashop17:
    image: prestashop/prestashop:1.7.3
    depends_on:
      - db-ps17
    environment:
      - PS_DEV_MODE=0
      - PS_COUNTRY=ES
      - PS_DOMAIN=prestashop17-test.docker:8017
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps17
      - DB_NAME=prestashop17
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    ports:
      - "8017:80"
    extra_hosts:
    - "prestashop17-test.docker:127.0.0.1"

  prestashop-dev17:
    image: prestashop/prestashop:1.7.3
    depends_on:
      - db-dev17
    environment:
      - PS_DEV_MODE=1
      - PS_COUNTRY=ES
      - PS_DOMAIN=prestashop-dev.docker:8018
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-dev17
      - DB_NAME=ps-dev17
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    volumes:
      - ./:/var/www/html/modules/paylater
    ports:
      - "8018:80"
    extra_hosts:
    - "prestashop-dev.docker:127.0.0.1"

  prestashop-dev16:
    image: prestashop/prestashop:1.6.1.20
    depends_on:
    - db-dev16
    environment:
    - PS_DEV_MODE=1
    - PS_COUNTRY=ES
    - PS_DOMAIN=prestashop-dev.docker:8019
    - PS_FOLDER_ADMIN=adminTest
    - PS_FOLDER_INSTALL=installTest
    - PS_HANDLE_DYNAMIC_DOMAIN=1
    - PS_INSTALL_AUTO=1
    - DB_SERVER=db-dev16
    - DB_NAME=ps-dev16
    - DB_PREFIX=ps_
    - DB_PASSWD=password
    networks:
    - internal
    - public
    volumes:
    - ./:/var/www/html/modules/paylater
    ports:
    - "8019:80"
    extra_hosts:
    - "prestashop-dev.docker:127.0.0.1"

  db-dev16:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ps-dev16
    networks:
      - internal
  db-dev17:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ps-dev17
    networks:
      - internal

  db-ps17:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop17
    networks:
      - internal

  db-ps16:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop16
    networks:
      - internal

  db-ps15:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop15
    networks:
      - internal

  selenium:
    image: selenium/standalone-chrome:3.7.1
    networks:
      - public
    ports:
      - 4444:4444
    extra_hosts:
      - "prestashop15-test.docker:${DOCKERHOST}"
      - "prestashop16-test.docker:${DOCKERHOST}"
      - "prestashop17-test.docker:${DOCKERHOST}"
      - "prestashop-dev.docker:${DOCKERHOST}"

networks:
    internal:
    public:
