version: "2"

services:
  prestashop15:
    image: prestashop/prestashop:1.5
    depends_on:
      - db-ps15
    environment:
      - PS_DEV_MODE=1
      - PS_COUNTRY=es
      - PS_DOMAIN=prestashop15
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps15
      - DB_NAME=prestashop15
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    volumes:
      - ./:/var/www/html/modules/paylater
    ports:
      - "8015:80"
  prestashop16:
    image: prestashop/prestashop:1.6.1.14
    depends_on:
      - db-ps16
    environment:
      - PS_DEV_MODE=1
      - PS_COUNTRY=es
      - PS_DOMAIN=prestashop16
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps16
      - DB_NAME=prestashop16
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    volumes:
      - ./:/var/www/html/modules/paylater
    ports:
      - "8016:80"
  prestashop17:
    image: prestashop/prestashop:1.7.1.2
    depends_on:
      - db-ps17
    environment:
      - PS_DEV_MODE=1
      - PS_COUNTRY=es
      - PS_DOMAIN=prestashop17
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-ps17
      - DB_NAME=prestashop17
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    volumes:
      - ./:/var/www/html/modules/paylater
    ports:
      - "8017:80"
  prestashop-dev:
    image: prestashop/prestashop:1.6.1.14
    depends_on:
      - db-dev
    environment:
      - PS_DEV_MODE=1
      - PS_COUNTRY=es
      - PS_DOMAIN=prestashop-dev:8018
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - DB_SERVER=db-dev
      - DB_NAME=prestashop-dev
      - DB_PREFIX=ps_
      - DB_PASSWD=password
    networks:
      - internal
      - public
    volumes:
      - ./:/var/www/html/modules/paylater
    ports:
      - "8018:80"
  db-dev:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop-dev
    networks:
      - internal
    ports:
      - "2083:3306"
  db-ps17:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop17
    networks:
      - internal
    ports:
      - "2082:3306"
  db-ps16:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop16
    networks:
      - internal
    ports:
      - "2081:3306"
  db-ps15:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop15
    networks:
      - internal
    ports:
      - "2080:3306"
  selenium:
    image: selenium/standalone-chrome:3.4.0
    networks:
      - public
    ports:
      - "4444:4444"

networks:
    internal:
    public:
